@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20ifSwiaWF0IjoxNTgxOTUyMzU4LCJleHAiOjE1ODE5NTU5NTh9.TVvL-Bh2ExTXtFNwW0Plkx5saWThX3nx4hU7k5f6jHg

### For create token
POST {{host}}/auth/ HTTP/1.1
content-type: application/json

{
    "email": "example@example.com"
}

### for get user by id
GET {{host}}/user/1 HTTP/1.1
?token={{token}}


### For create account
POST {{host}}/account/ HTTP/1.1
content-type: application/json

{
    "label": "test4",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20ifSwiaWF0IjoxNTgxOTUyMzU4LCJleHAiOjE1ODE5NTU5NTh9.TVvL-Bh2ExTXtFNwW0Plkx5saWThX3nx4hU7k5f6jHg"
}

### For get account
GET {{host}}/account/1 HTTP/1.1
?token={{token}}